version: '3'

services:
  db:
    image: postgres:latest
    environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=docker
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"
  webapp:
    build:
      context: .
      dockerfile: DockerFile.dockerfile
    command: "mvn spring-boot:run"
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
          - POSTGRES_USER=docker
          - POSTGRES_PASSWORD=docker
          - POSTGRES_DB=docker



